### ISSUE TITLE
add test_result_id to edit_test_result_status

### ISSUE THREAD

**Issue by delmaamoun** [devolo/adaptavist#1]
I use the jenkins junit plugin for tm4j. The report structure does not have environment or comments, so I have to edit the test result status with the status from the original junit report.
The problem is when the same test is run multiple times (data driven). If I edit the test result status only by test_run_key and test_case_key, it keeps editing the same test result and leaves out the rest.
I need to include the test_result_id to this method so I can edit the correct test result.

**Comment by ststeinberg** [comment]
Hi @delmaamoun, the tm4j API only supports editing by key (i.e. /testrun/{testRunKey}/testcase/{testCaseKey}/testresult).

To avoid overwriting previous test results, you can use create_test_result to create new results for each run.
Alternatively, it might be a better option to create new test run/cycles for each new run.
