### ISSUE TITLE
Creation of Test Case

### ISSUE THREAD

**Issue by Mukheem** [devolo/adaptavist#3]
Can someone help me with the creation of Test Case. I don't see such a method/Function. Is this yet to be implemented or Ain't I landing on correct documentation ? I could see other methods/Functions such as create Test Runs, Test results etc etc but not Test case.

**Comment by ststeinberg** [comment]
Hi @Mukheem, you are right, this method is not implemented, because until today test cases are created/written only manually in Jira Test Management. Do you see the need to do this in an automated/scripted way?

**Comment by nikhilbidave** [comment]
@ststeinberg Yes we need this functionality, we are in the phase of automating our entire testing process where test cases will be created based on python's feature files. @Mukheem

**Comment by ststeinberg** [comment]
Hi @nikhilbidave, I see. Of course we can add this functionality.

Are there any specific requirements we need to take care about? Maybe could you provide some basic example of a feature file and the mapping to tm4j, i.e. how the appropriate test case would look like in Jira/tm4j?

**Comment by Mukheem** [comment]
We managed to do it for ourselves, @ststeinberg. Atleast for now.  But this can help wider audience in getting things done easily. May be we can make Project Key and Test case name as mandatory argument and the rest to defaults. If the user would like to provide Folder, Steps etc etc then he shall take care of other Params. [Please bear with me if I sound like a novice. Not a beginner though. :D ]

I found Project Key is the only one thing besides its name is required to create a test case even it does not have specific steps /description etc etc.
@nikhilbidave , If missed anything, Feel free to add.
