### ISSUE TITLE
Potential dependency conflicts between adaptavist and requests

### ISSUE THREAD

**Issue by NeolithEra** [devolo/adaptavist#4]
Hi, as shown in the following full dependency graph of  **_adaptavist_**, **_adaptavist_** requires _**requests**_ (the latest version)， while the installed version of **_requests-toolbelt_**(0.9.1) requires _**requests>=2.0.1,<3.0.0**_.

According to Pip's “first found wins” installation strategy, _**requests 2.23.0**_ is the actually installed version.  

Although the first found package version _**requests 2.23.0**_ just satisfies the later dependency constraint （_**requests>=2.0.1,<3.0.0**_), it will lead to a build failure once developers release a newer version of requests.

### Dependency tree--------
```
adaptavist - 1.1.0
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- requests-toolbelt(install version:0.9.1 version range:*)
| | +- requests(install version:2.23.0 version range:>=2.0.1,<3.0.0)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_requests_** to be **_<=2.23.0_**.
2.	Remove your direct dependency **_requests_**, and use the **_requests_** transitively introduced by **_requests-toolbelt_**.


@ststeinberg Which solution do you prefer, 1 or 2?

**Comment by adrianer** [comment]
@NeolithEra : neither solution (especially option 1 would not loosen but tighten the requirements). The problem is only on the requests-toolbelt side, as there are the tight requirements. So requests-toolbelt must fix it.
