### ISSUE TITLE
Add possibility to skip SSL verification

### ISSUE THREAD

**Issue by petr0ff** [devolo/adaptavist#53]
Please, add possibiilty to init Adaptavist client with verify=False for requests methods. For API in our Jira there was changed the way of authentication and server now yells about SSL certificate errors. While request module has verify argument for it's HTTP requests method, we cannot override adaptavist client methods call with adding verify=False. Suggestion is to add ssl_verification field to init method (with default value True).

**Comment by 2Fake** [comment]
Added with release 2.4.0
